name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run make4ht
      uses: michal-h21/make4ht-action@master
      env:
        command: 'make4ht -c config.cfg -ua -l debug -d out main.tex "fn-in"'
    - name: Publish the web pages
      uses:  peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
        #deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        #publish_branch: main
